export const chatConstants = {
  CONNECTION_REQUEST : 'CHAT_CONNECTION_REQUEST',
  CONNECTION_SUCCESS : 'CHAT_CONNECTION_SUCCESS',
  CONNECTION_FAILURE : 'CHAT_CONNECTION_FAILURE',

  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_FAILURE: 'ADD_USER_FAILURE',

  MESSAGE_USER_LIST_SUCCESS: 'MESSAGE_USER_LIST_SUCCESS',
  MESSAGE_USER_LIST_FAILURE: 'MESSAGE_USER_LIST_FAILURE',

  LEAVE_ROOM_REQUEST : 'CHAT_LEAVE_ROOM_REQUEST',
  LEAVE_ROOM_SUCCESS : 'CHAT_LEAVE_ROOM_SUCCESS',
  LEAVE_ROOM_FAILURE : 'CHAT_LEAVE_ROOM_FAILURE',

  SEND_MESSAGE : 'CHAT_SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS : 'CHAT_SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE : 'CHAT_SEND_MESSAGE_FAILURE',

  RECEIVE_MESSAGE : 'CHAT_RECEIVE_MESSAGE_REQUEST',
  RECEIVE_MESSAGE_SUCCESS : 'CHAT_RECEIVE_MESSAGE_SUCCESS',
  RECEIVE_MESSAGE_FAILURE : 'CHAT_RECEIVE_MESSAGE_FAILURE',

  'TYPING_IDDLE' : 'CHAT_USER_NOT_TYPING',
  'TYPING_ACTIVE' : 'CHAT_USER_TYPING',

  SET_USERNAME_REQUEST: 'CHAT_SET_USERNAME_REQUEST',
  SET_USERNAME_SUCCESS: 'CHAT_SET_USERNAME_SUCCESS',
  SET_USERNAME_FAILURE: 'CHAT_SET_USERNAME_FAILURE',

}
