export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GET_SELF_REQUEST: 'USERS_GET_SELF_REQUEST',
    GET_SELF_SUCCESS: 'USERS_GET_SELF_SUCCESS',
    GET_SELF_FAILURE: 'USERS_GET_SELF_FAILURE',

};
